services:
  garage:
    env_file:
      - .env.development
    ports:
      - "127.0.0.1:3900:3900"
      - "127.0.0.1:3901:3901"
      - "127.0.0.1:3902:3902"
      - "127.0.0.1:3903:3903"

  garage-init:
    env_file:
      - .env.development

  prometheus:
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/alerts:/etc/prometheus/alerts:ro
  grafana:
    env_file:
      - .env.development
    environment:
      GF_SERVER_ROOT_URL: http://localhost:3001/
    ports:
      - "3001:3000"
  tempo:
    ports:
      - "127.0.0.1:3200:3200"
  alloy:
    ports:
      - "127.0.0.1:12345:12345"
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
  loki:
    ports:
      - "127.0.0.1:3100:3100"
  postgres:
    env_file:
      - .env.development
    ports:
      - "5432:5432"
