minimumReleaseAge: 1440
blockExoticSubdeps: true
allowBuilds:
  argon2: true
  cpu-features: true
  electron: true
  esbuild: true
  lefthook: false
  lightningcss: true
  msw: false
  protobufjs: false
  sharp: true
  ssh2: true
