packages:
  - "."
  - "packages/*"
  - "tools/*"

ignoreWorkspaceRootCheck: true

syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true

catalog:
  "@aws-sdk/client-s3": "^3.1066.0"
  dotenv: "^17.3.1"
  drizzle-kit: "1.0.0-rc.4"
  drizzle-orm: "1.0.0-rc.4"
  drizzle-seed: "1.0.0-rc.4"
  nanoid: "5.1.15"
  p-retry: "^8.0.0"
  pg: "^8.22.0"
  pg-boss: "^12.26.0"
  pino: "^10.3.1"
  tsx: "^4.22.4"

minimumReleaseAge: 1440
blockExoticSubdeps: true
allowBuilds:
  argon2: false
  cpu-features: false
  electron: false
  esbuild: true
  lefthook: true
  lightningcss: true
  msw: false
  protobufjs: false
  sharp: false
  ssh2: false
minimumReleaseAgeExclude:
  - "@oxfmt/binding-android-arm-eabi@0.56.0 || 0.60.0"
  - "@oxfmt/binding-android-arm64@0.56.0 || 0.60.0"
  - "@oxfmt/binding-darwin-arm64@0.56.0 || 0.60.0"
  - "@oxfmt/binding-darwin-x64@0.56.0 || 0.60.0"
  - "@oxfmt/binding-freebsd-x64@0.56.0 || 0.60.0"
  - "@oxfmt/binding-linux-arm-gnueabihf@0.56.0 || 0.60.0"
  - "@oxfmt/binding-linux-arm-musleabihf@0.56.0 || 0.60.0"
  - "@oxfmt/binding-linux-arm64-gnu@0.56.0 || 0.60.0"
  - "@oxfmt/binding-linux-arm64-musl@0.56.0 || 0.60.0"
  - "@oxfmt/binding-linux-ppc64-gnu@0.56.0 || 0.60.0"
  - "@oxfmt/binding-linux-riscv64-gnu@0.56.0 || 0.60.0"
  - "@oxfmt/binding-linux-riscv64-musl@0.56.0 || 0.60.0"
  - "@oxfmt/binding-linux-s390x-gnu@0.56.0 || 0.60.0"
  - "@oxfmt/binding-linux-x64-gnu@0.56.0 || 0.60.0"
  - "@oxfmt/binding-linux-x64-musl@0.56.0 || 0.60.0"
  - "@oxfmt/binding-openharmony-arm64@0.56.0 || 0.60.0"
  - "@oxfmt/binding-win32-arm64-msvc@0.56.0 || 0.60.0"
  - "@oxfmt/binding-win32-ia32-msvc@0.56.0 || 0.60.0"
  - "@oxfmt/binding-win32-x64-msvc@0.56.0 || 0.60.0"
  - "@oxlint/binding-android-arm-eabi@1.71.0 || 1.75.0"
  - "@oxlint/binding-android-arm64@1.71.0 || 1.75.0"
  - "@oxlint/binding-darwin-arm64@1.71.0 || 1.75.0"
  - "@oxlint/binding-darwin-x64@1.71.0 || 1.75.0"
  - "@oxlint/binding-freebsd-x64@1.71.0 || 1.75.0"
  - "@oxlint/binding-linux-arm-gnueabihf@1.71.0 || 1.75.0"
  - "@oxlint/binding-linux-arm-musleabihf@1.71.0 || 1.75.0"
  - "@oxlint/binding-linux-arm64-gnu@1.71.0 || 1.75.0"
  - "@oxlint/binding-linux-arm64-musl@1.71.0 || 1.75.0"
  - "@oxlint/binding-linux-ppc64-gnu@1.71.0 || 1.75.0"
  - "@oxlint/binding-linux-riscv64-gnu@1.71.0 || 1.75.0"
  - "@oxlint/binding-linux-riscv64-musl@1.71.0 || 1.75.0"
  - "@oxlint/binding-linux-s390x-gnu@1.71.0 || 1.75.0"
  - "@oxlint/binding-linux-x64-gnu@1.71.0 || 1.75.0"
  - "@oxlint/binding-linux-x64-musl@1.71.0 || 1.75.0"
  - "@oxlint/binding-openharmony-arm64@1.71.0 || 1.75.0"
  - "@oxlint/binding-win32-arm64-msvc@1.71.0 || 1.75.0"
  - "@oxlint/binding-win32-ia32-msvc@1.71.0 || 1.75.0"
  - "@oxlint/binding-win32-x64-msvc@1.71.0 || 1.75.0"
  - oxfmt@0.56.0 || 0.60.0
  - oxlint@1.71.0 || 1.75.0
  - "@tanstack/devtools-bundler-core@0.1.1"
  - "@tanstack/devtools-vite@0.8.3"
  - "@tanstack/devtools@0.13.0"
  - "@tanstack/react-devtools@0.10.9"
  - argon2@0.45.1
