apiVersion: 1

contactPoints:
  - orgId: 1
    name: Snack Rate Email
    receivers:
      - uid: snack-rate-email
        type: email
        disableResolveMessage: false
        settings:
          addresses: $GF_SMTP_USER
          singleEmail: true

policies:
  - orgId: 1
    receiver: Snack Rate Email
    group_by: ["..."]
