distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
overrides:
  defaults:
    compaction:
      compaction_disabled: true
querier:
  max_concurrent_queries: 10
query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1073741824
server:
  http_listen_port: 3200
  log_level: info
storage:
  trace:
    backend: local
    local:
      path: /var/tempo/blocks
    wal:
      path: /var/tempo/wal
