/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as HealthReadyRouteImport } from './routes/health.ready'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as LayoutTestRouteImport } from './routes/_layout/test'
import { Route as LayoutDodajProduktIndexRouteImport } from './routes/_layout/dodaj-produkt/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as LayoutProduktSlugRouteImport } from './routes/_layout/produkt/$slug'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => HealthRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTestRoute = LayoutTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDodajProduktIndexRoute = LayoutDodajProduktIndexRouteImport.update({
  id: '/dodaj-produkt/',
  path: '/dodaj-produkt/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutProduktSlugRoute = LayoutProduktSlugRouteImport.update({
  id: '/produkt/$slug',
  path: '/produkt/$slug',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/health': typeof HealthRouteWithChildren
  '/test': typeof LayoutTestRoute
  '/api/$': typeof ApiSplatRoute
  '/health/ready': typeof HealthReadyRoute
  '/produkt/$slug': typeof LayoutProduktSlugRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dodaj-produkt/': typeof LayoutDodajProduktIndexRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRouteWithChildren
  '/test': typeof LayoutTestRoute
  '/api/$': typeof ApiSplatRoute
  '/health/ready': typeof HealthReadyRoute
  '/': typeof LayoutIndexRoute
  '/produkt/$slug': typeof LayoutProduktSlugRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dodaj-produkt': typeof LayoutDodajProduktIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/health': typeof HealthRouteWithChildren
  '/_layout/test': typeof LayoutTestRoute
  '/api/$': typeof ApiSplatRoute
  '/health/ready': typeof HealthReadyRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/produkt/$slug': typeof LayoutProduktSlugRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_layout/dodaj-produkt/': typeof LayoutDodajProduktIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/test'
    | '/api/$'
    | '/health/ready'
    | '/produkt/$slug'
    | '/api/rpc/$'
    | '/dodaj-produkt/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/test'
    | '/api/$'
    | '/health/ready'
    | '/'
    | '/produkt/$slug'
    | '/api/rpc/$'
    | '/dodaj-produkt'
  id:
    | '__root__'
    | '/_layout'
    | '/health'
    | '/_layout/test'
    | '/api/$'
    | '/health/ready'
    | '/_layout/'
    | '/_layout/produkt/$slug'
    | '/api/rpc/$'
    | '/_layout/dodaj-produkt/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  HealthRoute: typeof HealthRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof HealthRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/test': {
      id: '/_layout/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof LayoutTestRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/dodaj-produkt/': {
      id: '/_layout/dodaj-produkt/'
      path: '/dodaj-produkt'
      fullPath: '/dodaj-produkt/'
      preLoaderRoute: typeof LayoutDodajProduktIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/produkt/$slug': {
      id: '/_layout/produkt/$slug'
      path: '/produkt/$slug'
      fullPath: '/produkt/$slug'
      preLoaderRoute: typeof LayoutProduktSlugRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutTestRoute: typeof LayoutTestRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProduktSlugRoute: typeof LayoutProduktSlugRoute
  LayoutDodajProduktIndexRoute: typeof LayoutDodajProduktIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutTestRoute: LayoutTestRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProduktSlugRoute: LayoutProduktSlugRoute,
  LayoutDodajProduktIndexRoute: LayoutDodajProduktIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

interface HealthRouteChildren {
  HealthReadyRoute: typeof HealthReadyRoute
}

const HealthRouteChildren: HealthRouteChildren = {
  HealthReadyRoute: HealthReadyRoute,
}

const HealthRouteWithChildren =
  HealthRoute._addFileChildren(HealthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  HealthRoute: HealthRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
